### ISSUE TITLE
I met the same issue, did you resolve it?

### ISSUE THREAD

**Issue by IanXia** [RobinYang11/nset-mongo-demo#1]

**Comment by IanXia** [comment]
add MongooseModule.forFeature in the export section in the module

**Comment by simultsop** [comment]
> add MongooseModule.forFeature in the export section in the module

@IanXia what do you mean add MongooseModule.forFeature ?

**Comment by simultsop** [comment]
After some digging in the discord,

it turned out that you have to state connection name (assuming you are using any, since that is where the bug is raising) right next to model injection inside service.

E.g.:


@Injectable()
export class EntityService {
  constructor(
    @InjectModel(Entity.name, 'defaultDB')

**Comment by IanXia** [comment]
> 

@simultsop you are correct, but I injected the schema name in module file, for example,

@Module({
    imports:[
      MongooseModule.forFeature([
        { name: User.name, schema: UserSchema },
      ]),   
      ConfigManageModule,
      PlatformApiModule
    ],
    providers: [UsersService],
    exports: [UsersService,
      MongooseModule.forFeature([
        { name: User.name, schema: UserSchema },
      ])
    ],
    controllers: [UsersController],
  })
export class UsersModule {}

**Comment by simultsop** [comment]
Interesting, didn't know that is possible. Though it looks weird to export Mongoose stuff.
Since stuff are still fresh and these edge cases hopefully are being worked out.

And we stop hacking xD

**Comment by IanXia** [comment]
I think it is reasonable,  because I called the function of mongoose in my service and I exported this service, so I think I exposed the data struct of mongo to the else module, then we need to export them.
